#--Key-Bindings-----------------------------------------------------------------
bind | split-window -h
bind _ split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U

#--Usability--------------------------------------------------------------------
set-option -g status-keys vi
set-window-option -g mode-keys vi
