local ns = { noremap = true, silent = true }

local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, ns)
vim.keymap.set('n', '<leader>fb', builtin.buffers, ns)
vim.keymap.set('n', '<leader>g', builtin.live_grep, ns)
vim.keymap.set('n', '<leader>s', builtin.treesitter, ns)
vim.keymap.set('n', '<leader>S', builtin.lsp_dynamic_workspace_symbols, ns)
vim.keymap.set('n', '<leader>h', builtin.help_tags, ns)
vim.keymap.set('n', '<leader>Q', builtin.quickfix, ns)
vim.keymap.set('n', '<leader>r', builtin.registers, ns)
vim.keymap.set('n', '<leader>R', builtin.resume, ns)
vim.keymap.set('n', '<leader>gb', builtin.git_branches, ns)
vim.keymap.set('n', '<leader>gs', builtin.git_status, ns)
vim.keymap.set('n', '<leader>gt', builtin.git_stash, ns)
